# Generated by Django 4.2.6 on 2023-11-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='max_mentors',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='max_prof',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='max_students',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
